name: prep
description: Inspired by the C preprocessor, this package helps you manage your project with unique source code expressions.
repository: https://github.com/robmllze/prep
version: 0.1.2+1
environment:
  sdk: '>=2.13.4 <3.0.0'
dependencies:
  yaml: ^3.1.0 # https://pub.dev/packages/yaml
  meta: ^1.7.0 # https://pub.dev/packages/meta
dev_dependencies:
  lints: ^1.0.1