name: prep
description: "Inspired by the C preprocessor, this package helps you manage your project with unique
source code expressions. Web support included."
repository: https://github.com/robmllze/prep
version: 0.3.5
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  yaml: ^3.0.0 # https://pub.dev/packages/yaml
  meta: ^1.3.0 # https://pub.dev/packages/meta
dev_dependencies:
  lints: ^1.0.1